import type { ReportResponse } from '../lib/api';

interface ReportViewProps {
  report: ReportResponse;
}

export function ReportView({ report }: ReportViewProps) {
  const { architecture, risks, review, business_requirements, technical_requirements, known_facts } = report;

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="bg-surface rounded-[16px] border border-border p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center"
            style={{ background: 'linear-gradient(90deg, #FF9900, #F47C20)' }}>
            <svg className="w-5 h-5 text-background" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
              <polyline points="14,2 14,8 20,8" />
            </svg>
          </div>
          <div>
            <h2 className="text-lg font-heading font-bold text-text">Discovery Report</h2>
            <p className="text-xs text-muted">Generated by Atlas AI Solutions Architect</p>
          </div>
        </div>
        <div className="flex gap-2">
          <Badge label="Approved" color="success" />
          <Badge label={`${architecture.services.length} Services`} color="info" />
          <Badge label={`${risks.length} Risks`} color="warning" />
        </div>
      </div>

      {/* Review Score */}
      {review.score && (
        <div className="bg-surface rounded-[16px] border border-border p-6">
          <h3 className="text-sm font-medium text-text-secondary mb-4">Well-Architected Score</h3>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {Object.entries(review.score).map(([pillar, score]) => (
              <ScoreCard key={pillar} pillar={pillar} score={score} />
            ))}
          </div>
        </div>
      )}

      {/* Requirements */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-surface rounded-[16px] border border-border p-6">
          <h3 className="text-sm font-medium text-text-secondary mb-3">Business Requirements</h3>
          <ul className="space-y-2">
            {business_requirements.map((req, i) => (
              <li key={i} className="text-xs text-muted flex items-start gap-2">
                <span className="text-primary mt-0.5">•</span>
                {typeof req === 'string' ? req : JSON.stringify(req)}
              </li>
            ))}
            {business_requirements.length === 0 && (
              <li className="text-xs text-disabled">None recorded</li>
            )}
          </ul>
        </div>
        <div className="bg-surface rounded-[16px] border border-border p-6">
          <h3 className="text-sm font-medium text-text-secondary mb-3">Technical Requirements</h3>
          <ul className="space-y-2">
            {technical_requirements.map((req, i) => (
              <li key={i} className="text-xs text-muted flex items-start gap-2">
                <span className="text-info mt-0.5">•</span>
                {typeof req === 'string' ? req : JSON.stringify(req)}
              </li>
            ))}
            {technical_requirements.length === 0 && (
              <li className="text-xs text-disabled">None recorded</li>
            )}
          </ul>
        </div>
      </div>

      {/* Known Facts */}
      <div className="bg-surface rounded-[16px] border border-border p-6">
        <h3 className="text-sm font-medium text-text-secondary mb-3">Discovered Facts</h3>
        <div className="flex flex-wrap gap-2">
          {known_facts.map((f, i) => (
            <span key={i} className="px-2 py-1 bg-background rounded-lg text-[11px] text-text-secondary border border-border">
              {typeof f === 'object' && f.fact ? f.fact : String(f)}
            </span>
          ))}
        </div>
      </div>

      {/* Risks */}
      {risks.length > 0 && (
        <div className="bg-surface rounded-[16px] border border-border p-6">
          <h3 className="text-sm font-medium text-text-secondary mb-4">Risk Register</h3>
          <div className="space-y-3">
            {risks.map((risk, i) => (
              <div key={i} className="bg-background rounded-xl p-4 border border-border">
                <div className="flex items-center gap-2 mb-1">
                  <SeverityDot severity={risk.impact} />
                  <p className="text-sm font-medium text-text">{risk.risk}</p>
                </div>
                <p className="text-xs text-muted">Mitigation: {risk.mitigation}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Review Findings */}
      {review.findings.length > 0 && (
        <div className="bg-surface rounded-[16px] border border-border p-6">
          <h3 className="text-sm font-medium text-text-secondary mb-4">Review Findings</h3>
          <div className="space-y-3">
            {review.findings.map((finding, i) => (
              <div key={i} className="bg-background rounded-xl p-4 border border-border">
                <div className="flex items-center gap-2 mb-1">
                  <span className={`text-[10px] font-medium uppercase
                    ${finding.severity === 'critical' ? 'text-danger'
                      : finding.severity === 'major' ? 'text-warning'
                        : 'text-muted'}`}>
                    {finding.severity}
                  </span>
                  <span className="text-[10px] text-disabled">{finding.category}</span>
                </div>
                <p className="text-xs text-text-secondary">{finding.finding}</p>
                <p className="text-xs text-muted mt-1">→ {finding.recommendation}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function Badge({ label, color }: { label: string; color: 'success' | 'info' | 'warning' }) {
  const colors = {
    success: 'bg-success/10 border-success/20 text-success',
    info: 'bg-info/10 border-info/20 text-info',
    warning: 'bg-warning/10 border-warning/20 text-warning',
  };
  return (
    <span className={`px-2 py-0.5 rounded-full text-[10px] font-medium border ${colors[color]}`}>
      {label}
    </span>
  );
}

function ScoreCard({ pillar, score }: { pillar: string; score: number }) {
  const color = score >= 8 ? 'text-success' : score >= 6 ? 'text-warning' : 'text-danger';
  const label = pillar.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

  return (
    <div className="bg-background rounded-xl p-3 border border-border text-center">
      <p className={`text-xl font-bold font-heading ${color}`}>{score}</p>
      <p className="text-[10px] text-muted mt-1 capitalize">{label}</p>
    </div>
  );
}

function SeverityDot({ severity }: { severity: string }) {
  const color = severity === 'high' ? 'bg-danger' : severity === 'medium' ? 'bg-warning' : 'bg-muted';
  return <span className={`w-2 h-2 rounded-full ${color}`} />;
}
